name: build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 14.6.0
        uses: actions/setup-node@v3
        with:
          node-version: "14.6.0"

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Install npm packages
        run: |
          npm i
        env:
          CI: true

      - name: Build folders for npm
        run: |
          npm run build
        env:
          CI: true

      - name: NPM Publish Main
        if: github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}
          access: "public"

      - name: NPM Publish Develop
        if: github.ref == 'refs/heads/develop'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}
          tag: "develop"
          access: "public"
